### ISSUE TITLE
Problem: cardano-wallet doesn't (it seems) plug into fractalide.

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/cardano-wallet#7]
Solution: we develop on a fractal but distribute by pluging the fractal into fractalide.

So initially the first app will be cardano-wallet, when we distribute it, it should be via users downloading fractalide.

Maybe at some point we can expose a button; "open in hyperflow"  and it seamlessly opens in hyperflow because hyperflow was disabled. I mention this as I saw some changes coming into the cardano-wallet fvm that means implementations are diverging. Ideally we plug cardano-wallet into fractalide. One VM to unite them all, and in the darkness bind them.

Now maybe we need to look at the whole nix layer now?

**Comment by clacke** [comment]
Yes, as everything is a bit bare-bones at the moment, and we're finding out how to fit things together, it was easier to start with wallet pulling in fractalide rather than the other way around. We need to make it trivial to produce a fractal that can do both, so that it is simultaneously stand-alone testable, yet also hyperflow pluggable.

I want to get at least a proof of concept of both UI end and SL end before I start looking at the fractalization. Once we have fractalized it, we should provide a hello-world scaffold for others to clone and start their fractals from.
